# Generated by Django 2.2.11 on 2020-04-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('plz', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('email', models.EmailField(max_length=100)),
                ('contact_phone', models.PositiveIntegerField()),
                ('contact_mobile', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deliverer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('plz', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('email', models.EmailField(max_length=100)),
                ('contact_phone', models.PositiveIntegerField()),
                ('contact_mobile', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Deliverer',
                'verbose_name_plural': 'Deliverers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date_planned', models.DateTimeField()),
                ('delivery_date_executed', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bringmenow.Customer')),
                ('deliverer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bringmenow.Deliverer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['customer', 'order_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=40)),
                ('contact_name', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('plz', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('email', models.EmailField(max_length=100)),
                ('contact_phone', models.PositiveIntegerField()),
                ('contact_mobile', models.PositiveIntegerField()),
                ('recieve_orders', models.CharField(choices=[('MAIL', 'Email'), ('SMS', 'SMS'), ('WEB', 'Web')], default='SMS', max_length=10)),
                ('bank_account', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('ALCOHOL', 'Alcohol'), ('BAKED', 'Baked Goods'), ('BEVERAGES', 'Beverages'), ('FISH', 'Fish'), ('FRUITS', 'Fruits'), ('MEAT', 'Meat'), ('MILK', 'Milch'), ('OTHERS', 'Others'), ('VEGETABLES', 'Vegetables')], default='OTHERS', max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('vegan', models.BooleanField(default=False)),
                ('glutenfree', models.BooleanField(default=False)),
                ('nutfree', models.BooleanField(default=False)),
                ('unit', models.PositiveIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('stock', models.PositiveIntegerField()),
                ('reduction', models.PositiveIntegerField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bringmenow.Supplier')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_planned', models.PositiveIntegerField()),
                ('units_executed', models.PositiveIntegerField()),
                ('price_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bringmenow.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bringmenow.Product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['order', 'product'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bringmenow.Supplier'),
        ),
    ]
